changelog:
  exclude-labels:
    - changelog/ignore
  categories:
    - title: Added
      labels:
        - changelog/added
    - title: Changed
      labels:
        - changelog/changed
    - title: Fixed
      labels:
        - changelog/fixed
    - title: Deprecated
      labels:
        - changelog/deprecated
    - title: Removed
      labels:
        - changelog/removed
    - title: Security
      labels:
        - changelog/security
    - title: Dependencies
      labels:
        - changelog/dependencies
