run:
  timeout: 3m
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - testifylint
    - nolintlint
    - bodyclose
    - goimports
    - importas
    - ireturn
    - perfsprint
    - gocritic
    - paralleltest
    - importas
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true
  govet:
    enable-all: true
    disable:
      - shadow
  testifylint:
    enable-all: true
  nolintlint:
    require-explanation: true
    require-specific: true
  perfsprint:
    strconcat: false
  gocritic:
    enable-all: true
    disabled-checks:
      - importShadow
      - hugeParam
      - rangeValCopy
      - whyNoLint
      - unnamedResult
      - httpNoBody
  importas:
    no-extra-aliases: true
    alias:
      - pkg: io/fs
        alias: iofs
      - pkg: github.com/go-logr/logr/testing
        alias: tlog
      - pkg: github.com/pelletier/go-toml/v2/unstable
        alias: tomlu
      - pkg: github.com/Masterminds/semver/v3
        alias: semver
      - pkg: github.com/multiformats/go-multiaddr/net
        alias: manet
      - pkg: github.com/multiformats/go-multiaddr
        alias: ma
      - pkg: github.com/multiformats/go-multicodec
        alias: mc
      - pkg: github.com/multiformats/go-multihash
        alias: mh
      - pkg: github.com/ipfs/go-cid
        alias: cid
      - pkg: github.com/libp2p/go-libp2p-kad-dht
        alias: dht
      - pkg: github.com/libp2p/go-libp2p/p2p/net/mock
        alias: mocknet
      - pkg: go.etcd.io/bbolt
        alias: bolt
      - pkg: k8s.io/cri-api/pkg/apis/runtime/v1
        alias: runtimeapi
      - pkg: github.com/containerd/containerd/api/events
        alias: eventtypes
      - pkg: github.com/opencontainers/go-digest
        alias: digest
      - pkg: github.com/opencontainers/image-spec/specs-go/v1
        alias: ocispec
