version: 2
project_name: spegel
before:
  hooks:
    - go mod tidy
builds:
  - goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
      - -a
    no_unique_dist_dir: true
    binary: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}/{{ .ProjectName }}"
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

dockers_v2:
  - images:
      - "harbor.infini-ai.com/mizar/spegel-org/spegel"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:                            # 一次性声明所有目标平台
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile
