{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spegel.fullname" . }}
  namespace: {{ include "spegel.namespace" . }}
  labels:
    {{- include "spegel.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.labels -}}
    {{ toYaml .Values.serviceMonitor.labels | nindent 4}}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "spegel.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
