{
 "title": "Spegel stateless cluster local OCI registry mirror",
 "description": "Spegel is a pull only OCI registry which runs locally on every Node in the Kubernetes cluster. Containerd is configured to use the local registry as a mirror, which would serve the image from within the cluster or from the source registry.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(spegel_advertised_content_digests,pod)"
    }
   },
   {
    "name": "registry",
    "label": "registry",
    "query": {
     "query": "label_values(spegel_advertised_content_digests,registry)"
    }
   },
   { "name": "container", "query": "registry" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(spegel_advertised_content_digests{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_node_name{job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kubelet_running_pods)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spegel_mirror_requests_total{pod=~\"$pod\", cache=\"hit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Miss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spegel_mirror_requests_total{pod=~\"$pod\", cache=\"miss\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(http_request_duration_seconds_bucket{pod=~\"$pod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Github link",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": {
    "content": "<br>\n<div style=\"text-align: center;\"><a href=\"https://github.com/XenitAB/spegel\" target=\"_blank\">Spegel at GitHub</a> </div>\n\n"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "datasource" },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "spegel_advertised_image_digests{pod=~\"$pod\", registry=~\"$registry\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spegel_advertised_content_digests{pod=~\"$pod\", registry=~\"$registry\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Images Advertised ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "spegel_advertised_image_digests{pod=~\"$pod\", registry=~\"$registry\"}",
     "legendFormat": "{{ pod }}: {{ registry }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"$container\"}) by (pod)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Images Layer Advertised ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "spegel_advertised_content_digests{pod=~\"$pod\", registry=~\"$registry\"} ",
     "legendFormat": "{{ pod }}: {{ registry }}"
    }
   ]
  },
  { "title": "Kubelet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Kubelet Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_total{job=\"kubelet\", metrics_path=\"/metrics\", operation_type=~\"list_images|pull_image|start_container|list_images|list_containers|version|exec_sync|create_container\"}[$__rate_interval])) by (operation_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubelet Operation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{job=\"kubelet\", metrics_path=\"/metrics\",operation_type=~\"list_images|pull_image|start_container|list_images|list_containers|version|exec_sync|create_container\"}[$__rate_interval])) by (operation_type)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  }
 ]
}