name: backport
on:
  pull_request_target:
    types: [closed, labeled]
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'closed' && github.event.pull_request.merged && (github.event_name != 'labeled' || startsWith('backport:', github.event.label.name))
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: bot
        with:
          client-id: ${{ secrets.PORTABOTTY_CLIENT_ID }}
          private-key: ${{ secrets.PORTABOTTY_PRIVATE_KEY }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write
          permission-pull-requests: write
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.bot.outputs.token }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Create backport PR
        uses: korthout/backport-action@66065406958f46e82238fd59546f5a99e69e22aa # v4.5.2
        with:
          github_token: ${{ steps.bot.outputs.token }}
          conflict_resolution: draft_commit_conflicts
          label_pattern: '^backport:([^ ]+)$'
          copy_labels_pattern: '^changelog\/\S+'
          pull_title: '[${target_branch}] ${pull_title}'
          pull_description: |-
            Automated backport to `${target_branch}`, triggered by a label in #${pull_number}.
