name: changelog
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
permissions:
  contents: read
defaults:
  run:
    shell: bash   
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check changelog label
        uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 #v5.6.0
        with:
          mode: exactly
          count: 1
          use_regex: true
          labels: "changelog/*"
