name: helm
on:
  pull_request:
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  verfiy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./charts/spegel
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Setup Helm unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git
      - name: Run lint
        run: helm lint .
      - name: Run tests
        run: helm unittest .
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c #v6.4.0
        with:
          go-version-file: go.mod
      - name: Generate docs
        run: make helm-docs
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git diff
            echo 'run make helm-docs and commit changes'
            exit 1
          fi
