name: helm
on:
  pull_request:
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  verfiy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./charts/spegel
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      - name: Setup Helm unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git
      - name: Run lint
        run: helm lint .
      - name: Run tests
        run: helm unittest .
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7.0.0
        with:
          go-version-file: go.mod
      - name: Generate docs
        run: make -B generate
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git diff
            echo 'run make generate and commit changes'
            exit 1
          fi
