name: helm
on:
  pull_request:
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  verfiy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./charts/spegel
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      - name: Setup Helm unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git
      - name: Run lint
        run: helm lint .
      - name: Run tests
        run: helm unittest .
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 #v6.5.0
        with:
          go-version-file: go.mod
      - name: Generate docs
        run: make -B generate
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git diff
            echo 'run make generate and commit changes'
            exit 1
          fi
